#!/usr/bin/env node
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { Command } from 'commander';
import { ManifestBuilder, validateManifest, BeekitClient } from '@hive/beekit-sdk';

const program = new Command();

program
  .name('hive-beekit')
  .description('CLI helper for building Bluesky/OpenClaw bots that integrate with Hive')
  .version('0.1.0');

program
  .command('init')
  .description('Scaffold a new bot project')
  .requiredOption('--name <name>', 'Bot name')
  .option('--dm', 'Enable DM interaction mode')
  .option('--dir <directory>', 'Project directory', '.')
  .action((opts) => {
    const projectDir = resolve(opts.dir);
    mkdirSync(projectDir, { recursive: true });

    const envPath = resolve(projectDir, '.env.example');
    if (!existsSync(envPath)) {
      writeFileSync(
        envPath,
        ['BLUESKY_IDENTIFIER=', 'BLUESKY_APP_PASSWORD=', 'HIVE_API_BASE_URL='].join('\n') + '\n'
      );
    }

    const manifest = new ManifestBuilder()
      .withName(opts.name)
      .withDescription(`${opts.name} generated by hive-beekit`)
      .withInteractionModes(opts.dm ? ['mention', 'dm'] : ['mention'])
      .withCapabilities(['respond'])
      .addCommand({ name: 'help', description: 'Show supported commands' });

    if (opts.dm) {
      manifest.withDmPolicy(true, 'ephemeral');
    }

    writeFileSync(resolve(projectDir, 'manifest.json'), JSON.stringify(manifest.build(), null, 2));
    console.log(`Initialized bot scaffold in ${projectDir}`);
  });

program
  .command('manifest')
  .description('Generate or validate manifest.json')
  .option('--validate', 'Validate existing manifest.json only')
  .option('--dir <directory>', 'Project directory', '.')
  .action((opts) => {
    const projectDir = resolve(opts.dir);
    const manifestPath = resolve(projectDir, 'manifest.json');

    if (opts.validate) {
      const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
      validateManifest(manifest);
      console.log('manifest.json is valid');
      return;
    }

    if (!existsSync(manifestPath)) {
      throw new Error('manifest.json not found. Run init first.');
    }

    const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
    validateManifest(manifest);
    writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n');
    console.log('manifest.json normalized and valid');
  });

program
  .command('dev')
  .description('Run local polling loop (placeholder, mention mode)')
  .requiredOption('--identifier <identifier>', 'Bluesky identifier')
  .requiredOption('--app-password <password>', 'Bluesky app password')
  .action(async (opts) => {
    const client = new BeekitClient({
      identifier: opts.identifier,
      appPassword: opts.appPassword,
      pollIntervalMs: 5_000
    });

    client.getRouter().use(async (message) => {
      console.log(`[${message.type}] ${message.authorDid}: ${message.text}`);
      return message;
    });

    await client.onMessage(async () => {
      // User-defined message handling would run here.
    });

    console.log('Beekit dev loop started. Press Ctrl+C to exit.');
  });

program
  .command('register')
  .description('Register bot with Hive registry')
  .requiredOption('--api-base-url <url>', 'Hive API base URL')
  .option('--manifest <path>', 'Path to manifest file', 'manifest.json')
  .action(async (opts) => {
    const manifestPath = resolve(opts.manifest);
    const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
    validateManifest(manifest);

    const response = await fetch(`${opts.apiBaseUrl}/bots`, {
      method: 'POST',
      headers: {
        'content-type': 'application/json'
      },
      body: JSON.stringify({
        did: manifest.did,
        handle: manifest.handle,
        display_name: manifest.display_name,
        description: manifest.description,
        categories: manifest.categories,
        operator_name: manifest.operator?.name,
        operator_email: manifest.operator?.email,
      })
    });

    if (!response.ok) {
      const body = await response.json().catch(() => ({ error: response.statusText }));
      throw new Error(`Hive register failed (${response.status}): ${(body as { error?: string }).error ?? 'unknown'}`);
    }

    const body = (await response.json()) as { data?: { listing_secret?: string; did?: string } };
    console.log(`Bot registered successfully.`);
    if (body.data?.listing_secret) {
      console.log(`\nListing secret (save this — it won't be shown again):\n  ${body.data.listing_secret}\n`);
    }
  });

program.parse(process.argv);
