#!/usr/bin/env node
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { Command } from 'commander';
import { ManifestBuilder, validateManifest, BeekitClient } from '@hive/beekit-sdk';

const program = new Command();

program
  .name('hive-beekit')
  .description('CLI helper for building Bluesky/OpenClaw bots that integrate with Hive')
  .version('0.1.0');

program
  .command('init')
  .description('Scaffold a new bot project')
  .requiredOption('--name <name>', 'Bot name')
  .option('--dm', 'Enable DM interaction mode')
  .option('--dir <directory>', 'Project directory', '.')
  .action((opts) => {
    const projectDir = resolve(opts.dir);
    mkdirSync(projectDir, { recursive: true });

    const envPath = resolve(projectDir, '.env.example');
    if (!existsSync(envPath)) {
      writeFileSync(
        envPath,
        ['BLUESKY_IDENTIFIER=', 'BLUESKY_APP_PASSWORD=', 'HIVE_API_BASE_URL=', 'HIVE_API_TOKEN='].join('\n') + '\n'
      );
    }

    const manifest = new ManifestBuilder()
      .withName(opts.name)
      .withDescription(`${opts.name} generated by hive-beekit`)
      .withInteractionModes(opts.dm ? ['mention', 'dm'] : ['mention'])
      .withCapabilities(['respond'])
      .addCommand({ name: 'help', description: 'Show supported commands' });

    if (opts.dm) {
      manifest.withDmPolicy(true, 'ephemeral');
    }

    writeFileSync(resolve(projectDir, 'manifest.json'), JSON.stringify(manifest.build(), null, 2));
    console.log(`Initialized bot scaffold in ${projectDir}`);
  });

program
  .command('manifest')
  .description('Generate or validate manifest.json')
  .option('--validate', 'Validate existing manifest.json only')
  .option('--dir <directory>', 'Project directory', '.')
  .action((opts) => {
    const projectDir = resolve(opts.dir);
    const manifestPath = resolve(projectDir, 'manifest.json');

    if (opts.validate) {
      const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
      validateManifest(manifest);
      console.log('manifest.json is valid');
      return;
    }

    if (!existsSync(manifestPath)) {
      throw new Error('manifest.json not found. Run init first.');
    }

    const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
    validateManifest(manifest);
    writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n');
    console.log('manifest.json normalized and valid');
  });

program
  .command('dev')
  .description('Run local polling loop (placeholder, mention mode)')
  .requiredOption('--identifier <identifier>', 'Bluesky identifier')
  .requiredOption('--app-password <password>', 'Bluesky app password')
  .action(async (opts) => {
    const client = new BeekitClient({
      identifier: opts.identifier,
      appPassword: opts.appPassword,
      pollIntervalMs: 5_000
    });

    client.getRouter().use(async (message) => {
      console.log(`[${message.type}] ${message.authorDid}: ${message.text}`);
      return message;
    });

    await client.onMessage(async () => {
      // User-defined message handling would run here.
    });

    console.log('Beekit dev loop started. Press Ctrl+C to exit.');
  });

program
  .command('register')
  .description('Sync bot metadata with Hive API')
  .requiredOption('--api-base-url <url>', 'Hive API base URL')
  .requiredOption('--api-token <token>', 'Hive API token')
  .option('--manifest <path>', 'Path to manifest file', 'manifest.json')
  .action(async (opts) => {
    const manifestPath = resolve(opts.manifest);
    const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
    validateManifest(manifest);

    const response = await fetch(`${opts.apiBaseUrl}/v1/bots/register`, {
      method: 'POST',
      headers: {
        authorization: `Bearer ${opts.apiToken}`,
        'content-type': 'application/json'
      },
      body: JSON.stringify({ manifest })
    });

    if (!response.ok) {
      throw new Error(`Hive register failed (${response.status})`);
    }

    const body = (await response.json()) as { listing_id?: string; status?: string };
    console.log(`Registered. Listing ID: ${body.listing_id ?? 'unknown'} (${body.status ?? 'ok'})`);
  });

program.parse(process.argv);
